export const SHOW_ALERT = "SHOW_ALERT"
export const HIDE_ALERT = "HIDE_ALERT"
export const CLEAR_USERS = "CLEAR_USERS"
export const GET_REPOS = "GET_REPOS"
export const GET_USER = "GET_USER"
export const SEARCH_USER = "SEARCH_USER"
export const SET_LOADING = "SET_LOADING"